### PR TITLE
First project in microverse

### PR DESCRIPTION
**Pull request by zainsadaqat**
I created my first web project in microverse which is "Hello Microverse" using HTML5 and CSS3. I used Git to track my files by following proper industry standards.

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
## Hi @zainsadaqat :raised_hands:

Good job so far!:clap::clap:
There are some issues that you still need to work on to go to the next project but you are almost there!!:muscle:

## Highlights 
 

*  You have descriptive Readme file:heavy_check_mark:
*  Your code are well organized:heavy_check_mark:

## Required Changes :recycle:

- [x] Kindly also add node_modules as part of .gitignore as it can be added by accident while setting up linters.
- [x] Make sure that the linters configuration are showing green instead of Red.
- [x] Please add the summary and descriptive Pull request.

## Optional suggestions

- [x] Better to commits your changes oftentimes instead of one time.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by zainsadaqat** [comment]
linters.yml is in green color at my side. what are you talking about?

**Comment by zainsadaqat** [comment]
From where to add the summary and descriptive Pull request? Please guide a little bit

**Comment by Emmyn5600** [comment]
@zainsadaqat , Once you created a new branch for deployment when you are pushing your changes you see a message saying to create a Pull request, so means that you can click on that or either click on a pull request after finishing your changes and choose to create a new pull to fill the descriptive PR.

**Comment by zainsadaqat** [comment]
Alright, Let me try

**Comment by zainsadaqat** [comment]
Please check out my description for Pull Request

**Review by arslanbisharat — APPROVED** [review]
# Approved 👏 

Hi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Pull request merged**
